language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
before_script:
  - chmod 0555 ./node_modules/.bin/travis-ci
install:
  - npm install
script:
  - npm test